import {
  SiReact,
  SiTypescript,
  SiTailwindcss,
  SiFramer,
  SiJavascript,
  SiHtml5,
  SiWebpack,
  SiFastapi,
  SiOpenapiinitiative,
  SiPython,
  SiHaskell,
  SiDocker,
  SiPandas,
  SiScikitlearn,
  SiSpacy,
  SiSelenium,
  SiPypi,
} from '@icons-pack/react-simple-icons';

export const SKILL_ICON_MAP: Record<string, typeof SiReact> = {
  react: SiReact,
  typescript: SiTypescript,
  tailwindcss: SiTailwindcss,
  framer: SiFramer,
  javascript: SiJavascript,
  html5: SiHtml5,
  webpack: SiWebpack,
  fastapi: SiFastapi,
  openapiinitiative: SiOpenapiinitiative,
  python: SiPython,
  haskell: SiHaskell,
  docker: SiDocker,
  pandas: SiPandas,
  scikitlearn: SiScikitlearn,
  spacy: SiSpacy,
  selenium: SiSelenium,
  pypi: SiPypi,
};